import type { AdminSectionConfig } from "@/types/admin";

export const adminSections: AdminSectionConfig[] = [
  {
    slug: "settings",
    title: "Site Settings",
    description: "Manage global labels, service details, footer content, and shared settings.",
    table: "site_settings",
    orderColumn: "label",
    ascending: true,
    supportsDelete: true,
    listColumns: ["label", "value", "group"],
    fields: [
      { name: "key", label: "Key", type: "text", required: true, placeholder: "hero_service_time" },
      { name: "label", label: "Label", type: "text", required: true, placeholder: "Service Time" },
      { name: "value", label: "Value", type: "textarea", required: true, placeholder: "Sundays at 10:30 AM" },
      { name: "group", label: "Group", type: "text", required: true, placeholder: "homepage" },
    ],
  },
  {
    slug: "navigation",
    title: "Navigation",
    description: "Control header and footer links, ordering, and visibility.",
    table: "navigation_items",
    orderColumn: "sort_order",
    ascending: true,
    supportsDelete: true,
    listColumns: ["label", "href", "location", "sort_order", "is_visible"],
    fields: [
      { name: "label", label: "Label", type: "text", required: true },
      { name: "href", label: "Href", type: "text", required: true, placeholder: "/events" },
      { name: "location", label: "Location", type: "select", required: true, options: [{ label: "Header", value: "header" }, { label: "Footer", value: "footer" }] },
      { name: "sort_order", label: "Sort Order", type: "number", required: true },
      { name: "is_visible", label: "Visible", type: "checkbox" },
    ],
  },
  {
    slug: "homepage",
    title: "Homepage Content",
    description: "Edit hero and supporting homepage sections, calls to action, and imagery.",
    table: "homepage_sections",
    orderColumn: "sort_order",
    ascending: true,
    supportsDelete: true,
    listColumns: ["section_key", "title", "sort_order", "is_enabled"],
    fields: [
      { name: "section_key", label: "Section Key", type: "text", required: true },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "subtitle", label: "Subtitle", type: "text" },
      { name: "body", label: "Body", type: "textarea" },
      { name: "cta_label", label: "CTA Label", type: "text" },
      { name: "cta_href", label: "CTA Href", type: "text" },
      { name: "secondary_cta_label", label: "Secondary CTA Label", type: "text" },
      { name: "secondary_cta_href", label: "Secondary CTA Href", type: "text" },
      { name: "image_url", label: "Image URL", type: "url" },
      { name: "sort_order", label: "Sort Order", type: "number", required: true },
      { name: "is_enabled", label: "Enabled", type: "checkbox" },
    ],
  },
  {
    slug: "sermons",
    title: "Sermons",
    description: "Publish sermon metadata and YouTube video links for the sermon library.",
    table: "sermons",
    orderColumn: "date",
    supportsDelete: true,
    listColumns: ["title", "speaker", "date", "is_published"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "speaker", label: "Speaker", type: "text", required: true },
      { name: "date", label: "Date", type: "date", required: true },
      { name: "scripture", label: "Scripture", type: "text" },
      { name: "summary", label: "Summary", type: "textarea" },
      { name: "thumbnail_url", label: "Thumbnail URL", type: "url" },
      { name: "youtube_url", label: "YouTube URL", type: "url", required: true },
      { name: "is_published", label: "Published", type: "checkbox" },
    ],
  },
  {
    slug: "events",
    title: "Events",
    description: "Manage upcoming events, schedules, locations, artwork, and RSVP links.",
    table: "events",
    orderColumn: "date",
    ascending: true,
    supportsDelete: true,
    listColumns: ["title", "date", "time", "location", "is_published"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "date", label: "Date", type: "date", required: true },
      { name: "time", label: "Time", type: "text", required: true },
      { name: "location", label: "Location", type: "text", required: true },
      { name: "image_url", label: "Image URL", type: "url" },
      { name: "rsvp_url", label: "RSVP URL", type: "url" },
      { name: "is_published", label: "Published", type: "checkbox" },
    ],
  },
  {
    slug: "announcements",
    title: "Announcements",
    description: "Feature timely notices and action links on the website.",
    table: "announcements",
    orderColumn: "publish_date",
    supportsDelete: true,
    listColumns: ["title", "publish_date", "expires_at", "is_published"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "body", label: "Body", type: "textarea", required: true },
      { name: "cta_label", label: "CTA Label", type: "text" },
      { name: "cta_href", label: "CTA Href", type: "text" },
      { name: "publish_date", label: "Publish Date", type: "date", required: true },
      { name: "expires_at", label: "Expires At", type: "date" },
      { name: "is_published", label: "Published", type: "checkbox" },
    ],
  },
  {
    slug: "contact-submissions",
    title: "Contact Submissions",
    description: "Review visitor messages and follow up with pastoral care or admin responses.",
    table: "contact_submissions",
    orderColumn: "created_at",
    listColumns: ["name", "email", "subject", "created_at"],
    readOnly: true,
    fields: [],
  },
  {
    slug: "new-here-submissions",
    title: "New Here Submissions",
    description: "Track newcomers, interests, and follow-up opportunities.",
    table: "new_here_submissions",
    orderColumn: "created_at",
    listColumns: ["name", "email", "phone", "created_at"],
    readOnly: true,
    fields: [],
  },
  {
    slug: "media",
    title: "Media",
    description: "Manage storage-backed assets for the site, sermons, and ministry content.",
    table: "media_assets",
    orderColumn: "created_at",
    listColumns: ["title", "bucket", "file_path", "created_at"],
    readOnly: true,
    fields: [],
  },
];

export const adminSectionsBySlug = Object.fromEntries(adminSections.map((section) => [section.slug, section]));

