import type {
  Announcement,
  ContactSubmission,
  EventItem,
  HomepageSection,
  Leader,
  MediaAsset,
  NavigationItem,
  NewHereSubmission,
  PageSection,
  Sermon,
  SiteSetting,
} from "@/types/cms";

export const demoSiteSettings: SiteSetting[] = [
  { key: "church_name", label: "Church Name", value: "Australian Kachin Christian Church", group: "general" },
  { key: "meta_default_title", label: "Default Meta Title", value: "AKCC | Australian Kachin Christian Church", group: "seo" },
  {
    key: "meta_default_description",
    label: "Default Meta Description",
    value: "Australian Kachin Christian Church welcomes people of all ages to worship, grow in faith, and find community.",
    group: "seo",
  },
  { key: "header_brand_label", label: "Header Brand Label", value: "Australian Kachin", group: "header" },
  { key: "header_secondary_cta_label", label: "Header Secondary CTA Label", value: "Latest Message", group: "header" },
  { key: "header_secondary_cta_href", label: "Header Secondary CTA Link", value: "/sermons", group: "header" },
  { key: "header_primary_cta_label", label: "Header Primary CTA Label", value: "Plan a Visit", group: "header" },
  { key: "header_primary_cta_href", label: "Header Primary CTA Link", value: "/new-here", group: "header" },
  { key: "hero_service_time_label", label: "Homepage Service Time Label", value: "Service Time", group: "homepage" },
  { key: "hero_service_time", label: "Service Time", value: "Sundays at 10:30 AM", group: "homepage" },
  { key: "hero_location_label", label: "Homepage Location Label", value: "Location", group: "homepage" },
  { key: "hero_location", label: "Location", value: "West Ryde Community Hall, Sydney", group: "homepage" },
  { key: "hero_cta_label", label: "Primary CTA Label", value: "Plan Your Visit", group: "homepage" },
  { key: "hero_cta_href", label: "Primary CTA Link", value: "/new-here", group: "homepage" },
  { key: "hero_secondary_cta_label", label: "Secondary CTA Label", value: "Watch Sermons", group: "homepage" },
  { key: "hero_secondary_cta_href", label: "Secondary CTA Link", value: "/sermons", group: "homepage" },
  { key: "footer_brand_label", label: "Footer Brand Label", value: "AKCC", group: "footer" },
  { key: "footer_navigation_heading", label: "Footer Navigation Heading", value: "Navigate", group: "footer" },
  { key: "footer_contact_heading", label: "Footer Contact Heading", value: "Contact", group: "footer" },
  {
    key: "footer_tagline",
    label: "Footer Tagline",
    value: "A welcoming Kachin church family growing in Christ across Australia.",
    group: "footer",
  },
  { key: "footer_address", label: "Footer Address", value: "West Ryde Community Hall, Sydney, NSW", group: "footer" },
  { key: "footer_email", label: "Footer Email", value: "hello@akcc.org.au", group: "footer" },
  { key: "footer_phone", label: "Footer Phone", value: "+61 400 000 000", group: "footer" },
  { key: "contact_address_label", label: "Contact Address Label", value: "Address", group: "contact" },
  { key: "contact_email_label", label: "Contact Email Label", value: "Email", group: "contact" },
  { key: "contact_phone_label", label: "Contact Phone Label", value: "Phone", group: "contact" },
  { key: "contact_service_label", label: "Contact Service Label", value: "Sunday Service", group: "contact" },
];

export const demoNavigation: NavigationItem[] = [
  { id: "nav-home", label: "Home", href: "/", sort_order: 1, is_visible: true, location: "header" },
  { id: "nav-about", label: "About", href: "/about", sort_order: 2, is_visible: true, location: "header" },
  { id: "nav-sermons", label: "Sermons", href: "/sermons", sort_order: 3, is_visible: true, location: "header" },
  { id: "nav-events", label: "Events", href: "/events", sort_order: 4, is_visible: true, location: "header" },
  { id: "nav-new-here", label: "New Here", href: "/new-here", sort_order: 5, is_visible: true, location: "header" },
  { id: "nav-contact", label: "Contact", href: "/contact", sort_order: 6, is_visible: true, location: "header" },
  { id: "foot-about", label: "About", href: "/about", sort_order: 1, is_visible: true, location: "footer" },
  { id: "foot-sermons", label: "Sermons", href: "/sermons", sort_order: 2, is_visible: true, location: "footer" },
  { id: "foot-events", label: "Events", href: "/events", sort_order: 3, is_visible: true, location: "footer" },
  { id: "foot-contact", label: "Contact", href: "/contact", sort_order: 4, is_visible: true, location: "footer" },
];

export const demoHomepageSections: HomepageSection[] = [
  {
    id: "home-hero",
    section_key: "hero",
    title: "A church family rooted in faith, worship, and community.",
    subtitle: "Welcome to AKCC",
    body: "Join us each Sunday as we gather to worship Jesus, encourage one another, and serve the Kachin community across Australia.",
    cta_label: "Plan Your Visit",
    cta_href: "/new-here",
    secondary_cta_label: "Explore Sermons",
    secondary_cta_href: "/sermons",
    image_url: "https://images.unsplash.com/photo-1519491050282-cf00c82424b4?auto=format&fit=crop&w=1200&q=80",
    sort_order: 1,
    is_enabled: true,
  },
  {
    id: "home-community",
    section_key: "community",
    title: "A welcoming place for every generation.",
    subtitle: "Life Together",
    body: "From children and youth to families and elders, AKCC is a home where people grow in faith together and care for one another beyond Sunday gatherings.",
    cta_label: "Meet Our Church",
    cta_href: "/about",
    secondary_cta_label: null,
    secondary_cta_href: null,
    image_url: "https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=1200&q=80",
    sort_order: 2,
    is_enabled: true,
  },
  {
    id: "home-next-steps",
    section_key: "next_steps",
    title: "Take your next step with us.",
    subtitle: "New to AKCC",
    body: "Whether you are exploring faith, looking for a church home, or hoping to connect with our leaders, we would love to hear from you.",
    cta_label: "I'm New Here",
    cta_href: "/new-here",
    secondary_cta_label: "Contact Us",
    secondary_cta_href: "/contact",
    image_url: null,
    sort_order: 3,
    is_enabled: true,
  },
];

export const demoPageSections: PageSection[] = [
  {
    id: "page-home-expect",
    page_key: "home",
    section_key: "welcome_card_expect",
    title: "What to expect",
    subtitle: null,
    body: "Warm worship, biblical teaching, prayer, and a welcoming church family that makes space for people of every age and stage.",
    cta_label: null,
    cta_href: null,
    secondary_cta_label: null,
    secondary_cta_href: null,
    image_url: null,
    sort_order: 1,
    is_enabled: true,
  },
  {
    id: "page-home-belong",
    page_key: "home",
    section_key: "welcome_card_belong",
    title: "Who it's for",
    subtitle: null,
    body: "Families, students, working professionals, elders, newcomers, and anyone exploring Christian faith.",
    cta_label: null,
    cta_href: null,
    secondary_cta_label: null,
    secondary_cta_href: null,
    image_url: null,
    sort_order: 2,
    is_enabled: true,
  },
  {
    id: "page-home-sermons",
    page_key: "home",
    section_key: "sermons_intro",
    title: "Recent teaching to encourage your faith.",
    subtitle: "Latest Sermons",
    body: "Watch recent messages, revisit Sunday teaching, and share sermons with family and friends.",
    cta_label: null,
    cta_href: null,
    secondary_cta_label: null,
    secondary_cta_href: null,
    image_url: null,
    sort_order: 3,
    is_enabled: true,
  },
  {
    id: "page-home-events",
    page_key: "home",
    section_key: "events_intro",
    title: "Gather, grow, and serve together.",
    subtitle: "Upcoming Events",
    body: "Church life extends beyond Sunday. Stay connected through prayer gatherings, fellowship, and ministry events.",
    cta_label: null,
    cta_href: null,
    secondary_cta_label: null,
    secondary_cta_href: null,
    image_url: null,
    sort_order: 4,
    is_enabled: true,
  },
  {
    id: "page-home-leaders",
    page_key: "home",
    section_key: "leaders_intro",
    title: "Meet the people who help shepherd AKCC.",
    subtitle: "Leadership",
    body: "Our leaders are committed to pastoral care, prayer, discipleship, and building a church family centered on Christ.",
    cta_label: null,
    cta_href: null,
    secondary_cta_label: null,
    secondary_cta_href: null,
    image_url: null,
    sort_order: 5,
    is_enabled: true,
  },
  {
    id: "page-about-meta",
    page_key: "about",
    section_key: "meta",
    title: "About AKCC",
    subtitle: null,
    body: "Learn about Australian Kachin Christian Church, our mission, leadership, and church family in Sydney.",
    cta_label: null,
    cta_href: null,
    secondary_cta_label: null,
    secondary_cta_href: null,
    image_url: null,
    sort_order: 1,
    is_enabled: true,
  },
  {
    id: "page-about-hero",
    page_key: "about",
    section_key: "hero",
    title: "A church home shaped by worship, scripture, and loving community.",
    subtitle: "About AKCC",
    body: "AKCC exists to glorify God, nurture Kachin believers in Australia, and warmly welcome new people into the life of Christ-centered community.",
    cta_label: null,
    cta_href: null,
    secondary_cta_label: null,
    secondary_cta_href: null,
    image_url: null,
    sort_order: 2,
    is_enabled: true,
  },
  {
    id: "page-about-mission",
    page_key: "about",
    section_key: "mission",
    title: "Our Mission",
    subtitle: null,
    body: "To make disciples of Jesus Christ through worship, biblical teaching, prayer, pastoral care, and service.",
    cta_label: null,
    cta_href: null,
    secondary_cta_label: null,
    secondary_cta_href: null,
    image_url: null,
    sort_order: 3,
    is_enabled: true,
  },
  {
    id: "page-about-heart",
    page_key: "about",
    section_key: "heart",
    title: "Our Heart",
    subtitle: null,
    body: "We want every person who walks through our doors to feel seen, welcomed, and invited into genuine community.",
    cta_label: null,
    cta_href: null,
    secondary_cta_label: null,
    secondary_cta_href: null,
    image_url: null,
    sort_order: 4,
    is_enabled: true,
  },
  {
    id: "page-about-future",
    page_key: "about",
    section_key: "future",
    title: "Our Future",
    subtitle: null,
    body: "We are building a sustainable ministry foundation for the next generation, with strong pastoral care and digital reach.",
    cta_label: null,
    cta_href: null,
    secondary_cta_label: null,
    secondary_cta_href: null,
    image_url: null,
    sort_order: 5,
    is_enabled: true,
  },
  {
    id: "page-about-leadership",
    page_key: "about",
    section_key: "leadership_intro",
    title: "People serving with faithfulness and care.",
    subtitle: "Leadership Team",
    body: "AKCC's leaders help guide worship, discipleship, community support, and church-wide ministry rhythms.",
    cta_label: null,
    cta_href: null,
    secondary_cta_label: null,
    secondary_cta_href: null,
    image_url: null,
    sort_order: 6,
    is_enabled: true,
  },
  {
    id: "page-sermons-meta",
    page_key: "sermons",
    section_key: "meta",
    title: "Sermons",
    subtitle: null,
    body: "Watch recent AKCC sermons, replay Sunday messages, and share YouTube-based preaching with family and friends.",
    cta_label: null,
    cta_href: null,
    secondary_cta_label: null,
    secondary_cta_href: null,
    image_url: null,
    sort_order: 1,
    is_enabled: true,
  },
  {
    id: "page-sermons-hero",
    page_key: "sermons",
    section_key: "hero",
    title: "Watch recent preaching and revisit messages anytime.",
    subtitle: "Sermons",
    body: "AKCC sermons are published with YouTube embeds so members and visitors can stay connected throughout the week.",
    cta_label: null,
    cta_href: null,
    secondary_cta_label: null,
    secondary_cta_href: null,
    image_url: null,
    sort_order: 2,
    is_enabled: true,
  },
  {
    id: "page-sermons-featured",
    page_key: "sermons",
    section_key: "featured",
    title: "Featured Sermon",
    subtitle: null,
    body: "Highlighted message from the latest Sunday gathering.",
    cta_label: null,
    cta_href: null,
    secondary_cta_label: null,
    secondary_cta_href: null,
    image_url: null,
    sort_order: 3,
    is_enabled: true,
  },
  {
    id: "page-sermons-library",
    page_key: "sermons",
    section_key: "library",
    title: "Browse the latest messages.",
    subtitle: "Sermon Library",
    body: "Explore the full sermon archive and revisit messages at your own pace.",
    cta_label: null,
    cta_href: null,
    secondary_cta_label: null,
    secondary_cta_href: null,
    image_url: null,
    sort_order: 4,
    is_enabled: true,
  },
  {
    id: "page-events-meta",
    page_key: "events",
    section_key: "meta",
    title: "Events",
    subtitle: null,
    body: "See upcoming AKCC events, church gatherings, ministry moments, and RSVP opportunities.",
    cta_label: null,
    cta_href: null,
    secondary_cta_label: null,
    secondary_cta_href: null,
    image_url: null,
    sort_order: 1,
    is_enabled: true,
  },
  {
    id: "page-events-hero",
    page_key: "events",
    section_key: "hero",
    title: "Stay connected through worship, fellowship, and ministry life.",
    subtitle: "Events",
    body: "From family gatherings to prayer nights, our events help church life feel relational, intentional, and full of welcome.",
    cta_label: null,
    cta_href: null,
    secondary_cta_label: null,
    secondary_cta_href: null,
    image_url: null,
    sort_order: 2,
    is_enabled: true,
  },
  {
    id: "page-events-listing",
    page_key: "events",
    section_key: "listing_intro",
    title: "What's happening soon at AKCC.",
    subtitle: "Upcoming",
    body: "Browse upcoming gatherings and RSVP where needed.",
    cta_label: null,
    cta_href: null,
    secondary_cta_label: null,
    secondary_cta_href: null,
    image_url: null,
    sort_order: 3,
    is_enabled: true,
  },
  {
    id: "page-contact-meta",
    page_key: "contact",
    section_key: "meta",
    title: "Contact",
    subtitle: null,
    body: "Contact AKCC for prayer, pastoral care, visit questions, or general church enquiries.",
    cta_label: null,
    cta_href: null,
    secondary_cta_label: null,
    secondary_cta_href: null,
    image_url: null,
    sort_order: 1,
    is_enabled: true,
  },
  {
    id: "page-contact-hero",
    page_key: "contact",
    section_key: "hero",
    title: "We would love to hear from you.",
    subtitle: "Contact",
    body: "Reach out with questions, prayer needs, pastoral care requests, or anything else you'd like to share with AKCC.",
    cta_label: null,
    cta_href: null,
    secondary_cta_label: null,
    secondary_cta_href: null,
    image_url: null,
    sort_order: 2,
    is_enabled: true,
  },
  {
    id: "page-contact-card",
    page_key: "contact",
    section_key: "contact_card",
    title: "Visit or Contact",
    subtitle: null,
    body: "You can use the form to send general questions, prayer requests, pastoral care needs, or follow-up messages to the AKCC team.",
    cta_label: null,
    cta_href: null,
    secondary_cta_label: null,
    secondary_cta_href: null,
    image_url: null,
    sort_order: 3,
    is_enabled: true,
  },
  {
    id: "page-new-here-meta",
    page_key: "new-here",
    section_key: "meta",
    title: "New Here",
    subtitle: null,
    body: "Plan your first visit to AKCC, ask questions, and let our church family welcome you well.",
    cta_label: null,
    cta_href: null,
    secondary_cta_label: null,
    secondary_cta_href: null,
    image_url: null,
    sort_order: 1,
    is_enabled: true,
  },
  {
    id: "page-new-here-hero",
    page_key: "new-here",
    section_key: "hero",
    title: "Planning your first visit? We would love to welcome you.",
    subtitle: "New Here",
    body: "Whether you're exploring faith or looking for a church family, AKCC is a warm place to worship, connect, and belong.",
    cta_label: null,
    cta_href: null,
    secondary_cta_label: null,
    secondary_cta_href: null,
    image_url: null,
    sort_order: 2,
    is_enabled: true,
  },
  {
    id: "page-new-here-card",
    page_key: "new-here",
    section_key: "visit_card",
    title: "What to Expect",
    subtitle: null,
    body: "Expect heartfelt worship, clear Bible teaching, prayer, and a friendly church family ready to help you settle in.\n\nYou can use this form to let us know you're coming, ask questions, or share how we can help make your first visit comfortable.\n\nOur leaders can also connect you to small groups, children's ministry, youth gatherings, and serving opportunities.",
    cta_label: null,
    cta_href: null,
    secondary_cta_label: null,
    secondary_cta_href: null,
    image_url: null,
    sort_order: 3,
    is_enabled: true,
  },
];

export const demoSermons: Sermon[] = [
  {
    id: "sermon-1",
    title: "Faithful in Every Season",
    slug: "faithful-in-every-season",
    speaker: "Rev. Lahpai Zau",
    date: "2026-03-01",
    scripture: "Psalm 46",
    summary: "A message of steady trust in God during change, uncertainty, and transition.",
    thumbnail_url: "https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    is_published: true,
  },
  {
    id: "sermon-2",
    title: "The Beauty of Gospel Community",
    slug: "beauty-of-gospel-community",
    speaker: "Pastor Mung Nau",
    date: "2026-02-22",
    scripture: "Acts 2:42-47",
    summary: "How the early church models prayer, generosity, fellowship, and joyful witness for us today.",
    thumbnail_url: "https://img.youtube.com/vi/ysz5S6PUM-U/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/watch?v=ysz5S6PUM-U",
    is_published: true,
  },
  {
    id: "sermon-3",
    title: "Hope That Holds",
    slug: "hope-that-holds",
    speaker: "Rev. Gum Ja",
    date: "2026-02-15",
    scripture: "Hebrews 6:13-20",
    summary: "A call to anchor our hearts in the promises of God when life feels unstable.",
    thumbnail_url: "https://img.youtube.com/vi/jNQXAC9IVRw/hqdefault.jpg",
    youtube_url: "https://www.youtube.com/watch?v=jNQXAC9IVRw",
    is_published: true,
  },
];

export const demoEvents: EventItem[] = [
  {
    id: "event-1",
    title: "Youth Worship Night",
    slug: "youth-worship-night",
    description: "An evening of worship, testimonies, and prayer for our youth and young adults.",
    date: "2026-03-20",
    time: "7:00 PM",
    location: "Parramatta Community Centre",
    image_url: "https://images.unsplash.com/photo-1504052434569-70ad5836ab65?auto=format&fit=crop&w=1200&q=80",
    rsvp_url: "https://example.com/rsvp/youth-worship-night",
    is_published: true,
  },
  {
    id: "event-2",
    title: "Family Fellowship Lunch",
    slug: "family-fellowship-lunch",
    description: "A relaxed lunch after service for families, newcomers, and ministry leaders to connect.",
    date: "2026-03-29",
    time: "12:30 PM",
    location: "Church Hall",
    image_url: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=1200&q=80",
    rsvp_url: null,
    is_published: true,
  },
  {
    id: "event-3",
    title: "Prayer and Fasting Morning",
    slug: "prayer-and-fasting-morning",
    description: "A focused morning of worship and prayer for the church, our city, and mission partners.",
    date: "2026-04-04",
    time: "9:00 AM",
    location: "AKCC Prayer Room",
    image_url: null,
    rsvp_url: null,
    is_published: true,
  },
];

export const demoAnnouncements: Announcement[] = [
  {
    id: "announcement-1",
    title: "Volunteer Sign-ups Open",
    body: "We are welcoming more volunteers for hospitality, worship support, kids ministry, and Sunday setup teams.",
    cta_label: "Get Involved",
    cta_href: "/contact",
    publish_date: "2026-03-05",
    expires_at: null,
    is_published: true,
  },
  {
    id: "announcement-2",
    title: "Prayer Requests Welcome",
    body: "If you need prayer, our pastoral team would be honored to stand with you throughout the week.",
    cta_label: "Share a Request",
    cta_href: "/new-here",
    publish_date: "2026-03-08",
    expires_at: null,
    is_published: true,
  },
];

export const demoLeaders: Leader[] = [
  {
    id: "leader-1",
    name: "Rev. Lahpai Zau",
    role_title: "Senior Pastor",
    bio: "Serving AKCC with a heart for gospel preaching, pastoral care, and intergenerational discipleship.",
    image_url: null,
    email: "pastor@akcc.org.au",
    phone: null,
    sort_order: 1,
    is_published: true,
  },
  {
    id: "leader-2",
    name: "Maran Htoi",
    role_title: "Community Care Coordinator",
    bio: "Helps newcomers connect into fellowship, prayer, and practical support across the church family.",
    image_url: null,
    email: "care@akcc.org.au",
    phone: null,
    sort_order: 2,
    is_published: true,
  },
];

export const demoContactSubmissions: ContactSubmission[] = [
  {
    id: "contact-1",
    name: "Ja Seng",
    email: "jaseng@example.com",
    phone: "+61 401 555 333",
    subject: "Sunday visit",
    message: "My family is planning to visit this month and would love to know where to park.",
    created_at: "2026-03-09T08:00:00.000Z",
  },
];

export const demoNewHereSubmissions: NewHereSubmission[] = [
  {
    id: "new-here-1",
    name: "Nang Htoi",
    email: "nanghtoi@example.com",
    phone: "+61 412 333 222",
    household_size: 4,
    prayer_request: "Please pray for our family as we settle into Sydney.",
    interested_in: ["Sunday worship", "Small groups"],
    created_at: "2026-03-10T01:30:00.000Z",
  },
];

export const demoMediaAssets: MediaAsset[] = [
  {
    id: "media-1",
    title: "Homepage Hero",
    file_path: "homepage/hero-image.jpg",
    public_url: "https://images.unsplash.com/photo-1519491050282-cf00c82424b4?auto=format&fit=crop&w=1200&q=80",
    mime_type: "image/jpeg",
    bucket: "site-media",
    alt_text: "Church community gathered in worship",
    uploaded_by: null,
    created_at: "2026-03-01T00:00:00.000Z",
  },
];
